### ISSUE TITLE
How to check currently installed Natsumi version

### ISSUE THREAD

**Issue by kawaiier** [greeeen-dev/natsumi-browser#21]
Is there a way to check which version of Natsumi is currently installed and in use?

**Comment by greeeen-dev** [comment]
Not yet, but I'm considering it, just gotta figure out where the version info should be shown.

**Comment by kawaiier** [comment]
I think `natsumi.css` can be the file that shows the version and provides a link to this repository, as there is already some information present

**Comment by greeeen-dev** [comment]
This will now be added to the userChrome.css file generated by Bento (the one you can install through Zen Rices once it releases)
